// <auto-generated />
namespace Exernet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _1stmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1stmig));
        
        string IMigrationMetadata.Id
        {
            get { return "201408061101281_1st mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
